apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: manifest-demo
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: https://github.com/javibc1/Helm-Demo.git
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "main"
  - name: IMAGE
    type: string
    description: image to be build from the code
    default: quay.io/f_bernal_cerpa/demo:latest
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    # - name: subdirectory
    #   value: "simple-js"
    - name: revision
      value: $(params.git-revision)
    - name: deleteExisting
      value: "true"
  - name: change-manifest
    taskRef:
      name: change-manifest
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter: 
    - fetch-repository
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: change-manifest
spec:
  steps:
    - name: check-files
      image: ubuntu
      command: ['ls', '-lhR']
    - name: change-manifest
      image: ubuntu
      command:
      - /bin/bash
      args:
      - -c
      - |
        set -ex
        find . -type f -name "*.yaml" -print0 | xargs -0 sed -i -e 's/$NAME/demo-sed/g' -e 's/$PROJECT/demo/g' -e 's/$IMAGE/quay.io\/f_bernal_cerpa\/demo:latest/g' -e 's/$REPLICAS/1/g'
    - name: git-push
      image: ubuntu
      command: ['ls', '-lhR']
  workspaces:
    - name: source
